---
deployment:
      tasks:
        - export DEPLOYPATH=/home/<username>/sd-offers             
        - /bin cp * $DEPLOYPATH                          
       
                  
        
        
