---
deployment:
      tasks:
        - export DEPLOYPATH=/home/wvlxjdhh/public_html/sd-twitter-offers  
        - /bin/cp public $DEPLOYPATH
        - /bin/cp sd-offers /home/wvlxjdhh/sd-offers                     
       
                  
        
        
